### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ajshedivy** [ajshedivy/tps#1]
**implementation features: run visualization without having Cytoscape open**
current set up:

-~~open Cytoscape desktop app on computer~~ fixed 
- move to ``visualization_scripts`` directory 
- run `bash activate.sh <output file> <style file>`
- open Cytoscape app to see applied style file

Update current feature:
Find a way to run bash command without Cytoscape open (convenience feature).
when bash command run without Cytoscape open error is thrown. Here is the full trace when run on my computer:
```
$ bash activate.sh output.sif style.xml
starting script
check enviornment
environment activated
<IPython.core.display.Javascript object>
output file: output.sif
style file: style.xml
Could not get status from CyREST:

HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /v1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ADED6127F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
None
Traceback (most recent call last):
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\urllib3\connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\http\client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\http\client.py", line 1152, in _send_request
    self.endheaders(body)
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\http\client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\http\client.py", line 934, in _send_output
    self.send(msg)
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\http\client.py", line 877, in send
    self.connect()
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\urllib3\connection.py", line 184, in connect
    conn = self._new_conn()
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001ADED626320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /v1/styles/visualproperties (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ADED626320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "visualize.py", line 60, in <module>
    main(sys.argv)
  File "visualize.py", line 42, in main
    cy = CyRestClient()
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\py2cytoscape\data\cyrest_client.py", line 19, in __init__
    self.style = StyleClient(self.__url)
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\py2cytoscape\data\style_client.py", line 16, in __init__
    self.vps = VisualProperties(url)
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\py2cytoscape\data\style_client.py", line 77, in __init__
    self.__convert_to_dict()
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\py2cytoscape\data\style_client.py", line 80, in __convert_to_dict
    vps = requests.get(self.__url).json()
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ajshe\Anaconda3\envs\py2cyto\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /v1/styles/visualproperties (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ADED626320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
end script
```

**Comment by agitter** [comment]
Can we close this now that https://github.com/gitter-lab/tps/pull/2 has been merged?
